name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - run: dart pub get

      - name: Run build.dart script
        run: dart build.dart

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
