name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - run: dart pub get

      - name: Run build.dart script
        run: dart build.dart -v

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output

      - name: Upload to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: UoM_Enhancements.xpi
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
