name: ESLint

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/eslint.yml"
      - "scripts/**"
      - "package.json"
      - ".eslintrc.js"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/eslint.yml"
      - "scripts/**"
      - "package.json"
      - ".eslintrc.js"
  schedule:
    # Run at 1:45am every Wednesday
    - cron: '45 1 * * 3'
  workflow_dispatch:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: npm install

      - name: Run ESLint
        run: npx eslint scripts
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
